myApp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^', include('userdb.urls')),
]

userdb/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

# add a namespace for better loose coupled reference of url within templates
app_name = "userdb"

# define the major urls for list, add and home pages
urlpatterns = [
	url(r'^add/', views.add_user, name='add'),
	url(r'^list/', views.ListUserView.as_view(), name='list'),
	url(r'^$', TemplateView.as_view(template_name="userdb/index.html"), name='index'),
]

userdb/models.py
from __future__ import unicode_literals
from django import forms
from django.db import models

# Create your models here.

class AppUser(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length=100)
	

userdb/forms.py
from django.forms import ModelForm, TextInput
from .models import AppUser

class AppUserForm(ModelForm):
	class Meta:
		model = AppUser
		fields = ('name', 'email')
		widgets = {
			'name': TextInput(attrs={'class':'form-control','placeholder':'User Name'}),
			'email': TextInput(attrs={'class':'form-control','placeholder':'user@email.com'})
		}
		labels = {
			'name':'Name',
			'email': 'Email'
		}

userdb/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import AppUser
from .forms import AppUserForm


# Create your views here.

def add_user(request):
	#check if the form has been submitted via post
	if request.method == 'POST':
		#create new instance of UserForm and populate it with POST data
		form = AppUserForm(request.POST)
		# check if form is valid
		if form.is_valid():
			# if form is valid, save to db
			form.save(commit=True)

			# redirect user to the lists page to see newly added user
			return HttpResponseRedirect(reverse('userdb:list'))

	else:
		# if page is being loaded for the first time,
		# return an empty form
		form = AppUserForm()
	
	#return either empty form for new page or populated form with validation errors.
	return render(request, 'userdb/add.html', {'form': form})


class ListUserView(ListView):
	model = AppUser
	template_name = 'userdb/list.html'

userdb/templates/userdb/add.html
{% extends "userdb/base.html" %}

{% block content %}
	<div class='container'>
		<div class="row">
			<div class="col-sm-6">
				<form class="text-xs-left" method='POST' action="">
					<h3>Add New User</h3>
					{{ form.non_field_errors }}
					{% csrf_token %}
					{% for field in form %}
					    <div class="form-group row">
							<div class="col-sm-2">{{ field.label_tag }}</div>
							<div class="col-sm-10">
								 {{ field }}
								<div class="form-control-feedback">{{ field.errors }}</div>
							</div>
						</div>
					{% endfor %}
					<input type='submit' value='Save' class='btn btn-lg btn-success' />
				</form>
				<hr><p>&nbsp;</p>
				<ul class='list-inline'>
					<li class='list-inline-item'><a href="{% url 'userdb:index' %}" class="btn btn-info">Home</a></li>
					<li class='list-inline-item'><a href="{% url 'userdb:list' %}" class="btn btn-primary">View All Users</a></li>
				</ul>
			</div>
		</div>
	</div>

{% endblock %}

userdb/templates/userdb/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta name="author" content="Okezie Arukwe">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">
		<title>My Django App</title>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
	</head>
	<body>
		<div class='jumbotron text-xs-center'>
			<h2>Hello, Friend!<br><small>Welcome to my Django App!</small></h2>
		</div>
		<div class='container'>
		{% block content %}
			Page content comes here
		{% endblock %}
		</div>
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
	</body>
</html>

userdb/templates/userdb/index.html
{% extends "userdb/base.html" %}

{% block content %}
	<div class='text-xs-center'>
		<p><strong>What do you want to do?</strong></p>
		<ul class='list-inline'>
			<li class='list-inline-item'><a href="{% url 'userdb:list' %}" class="btn btn-lg btn-primary">List All Users</a></li>
			<li class='list-inline-item'><a href="{% url 'userdb:add' %}" class="btn btn-lg btn-success">Add New User</a></li>
		</ul>
	</div>
{% endblock %}

userdb/templates/userdb/list.html
{% extends "userdb/base.html" %}

{% block content %}
	<div class='text-xs-center'>
		<h3>Users List</h3>
		<div class="table-responsive">
			<table class="table table-inverse text-xs-left">
				<thead><tr><th>UserID</th><th>Name</th><th>Email</th></tr></thead>
				<tbody>
					{% comment "Loop through the appuser objects and populate the table" %}
					{% endcomment %}
					{% for u in appuser_list %}
						<tr>
							<th scope="row">{{ forloop.counter }}</th>
							<td>{{ u.name }}</td>
							<td>{{ u.email }}</td>
						</tr>
					{% empty %}
						<caption class='alert alert-block alert-warning text-xs-center'>No User added yet!</caption>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<hr>
		<ul class='list-inline'>
			<li class='list-inline-item'><a href="{% url 'userdb:index' %}" class="btn btn-info">Home</a></li>
			<li class='list-inline-item'><a href="{% url 'userdb:add' %}" class="btn btn-success">Add New User</a></li>
		</ul>
	</div>
	
{% endblock %}